// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetLocationByIP(): $CancellablePromise<$models.IPLocation | null> {
    return $Call.ByID(3235047092).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetNativeLocation 呼叫 CoreLocation（macOS）取得裝置 GPS 位置。
 * 首次呼叫時會觸發系統授權對話框。
 */
export function GetNativeLocation(): $CancellablePromise<$models.NativeLocation | null> {
    return $Call.ByID(2608345875).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.IPLocation.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.NativeLocation.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
