// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class IPLocation {
    "ip": string;
    "city": string;
    "region": string;
    "country": string;
    "country_name": string;
    "latitude": number;
    "longitude": number;
    "timezone": string;
    "org": string;

    /** Creates a new IPLocation instance. */
    constructor($$source: Partial<IPLocation> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("city" in $$source)) {
            this["city"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("country_name" in $$source)) {
            this["country_name"] = "";
        }
        if (!("latitude" in $$source)) {
            this["latitude"] = 0;
        }
        if (!("longitude" in $$source)) {
            this["longitude"] = 0;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("org" in $$source)) {
            this["org"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPLocation instance from a string or object.
     */
    static createFrom($$source: any = {}): IPLocation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPLocation($$parsedSource as Partial<IPLocation>);
    }
}
