// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SearchLocation 依關鍵字搜尋地點，隨機回傳：空陣列、單筆或多筆結果。
 * query 為使用者輸入的搜尋字串（留待後端串接真實 API 時使用）。
 */
export function SearchLocation(query: string): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(4099355589, query).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SearchResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
